services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    container_name: llm-router-server
    volumes:
      - ./data:/data
    ports:
      - "8090:8080"
      - "9090:9090"
    networks: [ llmnet ]

networks:
  llmnet:
    external: true