FROM golang:1.22-alpine AS build
WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/node-agent ./cmd/node-agent

FROM alpine:3.20
WORKDIR /app
COPY --from=build /out/node-agent /app/node-agent
ENTRYPOINT ["/app/node-agent"]
